### ISSUE TITLE
Supported CID types 

### ISSUE THREAD

**Issue by FotiosBistas** [cortze/ipfs-cid-hoarder#12]
If I understand right currently the hoarder supports only the following CID type (which CIDv1): 
```go
// configure the type of CID that we want
pref := cid.Prefix{
	Version:  1,
	Codec:    cid.Raw,
	MhType:   mh.SHA2_256,
	MhLength: -1,
}
```
Would adding support for the rest CID types be beneficial? (CIDv0)

**Comment by cortze** [comment]
Do we plan to import any v0 CID? I would not bother too much here trying to make it compatible with v0 CIDs (unless I'm missing something)
